from enum import Enum


class EUFY_CLEAN_GET_STATE(str, Enum):
    sleeping = 'stopped'
    standby = 'docked'
    recharge = 'docked'
    running = 'cleaning'
    cleaning = 'cleaning'
    spot = 'spot_cleaning'
    completed = 'docked'
    charging = 'charging'
    sleep = 'stopped'
    go_home = 'docked'
    fault = 'stopped'


class EUFY_CLEAN_VACUUMCLEANER_STATE(str, Enum):
    STOPPED = 'stopped'
    CLEANING = 'cleaning'
    SPOT_CLEANING = 'spot_cleaning'
    DOCKED = 'docked'
    CHARGING = 'charging'


class EUFY_CLEAN_CLEAN_SPEED(str, Enum):
    NO_SUCTION = 'No_suction'
    STANDARD = 'Standard'
    QUIET = 'Quiet'
    TURBO = 'Turbo'
    BOOST_IQ = 'Boost_IQ'
    MAX = 'Max'


EUFY_CLEAN_NOVEL_CLEAN_SPEED = [
    EUFY_CLEAN_CLEAN_SPEED.QUIET,
    EUFY_CLEAN_CLEAN_SPEED.STANDARD,
    EUFY_CLEAN_CLEAN_SPEED.TURBO,
    EUFY_CLEAN_CLEAN_SPEED.MAX,
]

EUFY_CLEAN_LEGACY_CLEAN_SPEED = [
    EUFY_CLEAN_CLEAN_SPEED.NO_SUCTION,
    EUFY_CLEAN_CLEAN_SPEED.BOOST_IQ
]


class EUFY_CLEAN_GET_CLEAN_SPEED(str, Enum):
    no_suction = 'No Suction'
    standard = 'Standard'
    quiet = 'Quiet'
    turbo = 'Turbo'
    boost_iq = 'Boost IQ'
    max = 'Max'


class EUFY_CLEAN_WORK_STATUS(str, Enum):
    # Cleaning
    RUNNING = 'Running'
    # In the dock, charging
    CHARGING = 'Charging'
    # Not in the dock, paused
    STAND_BY = 'standby'
    # Not in the dock - goes into this state after being paused for a while
    SLEEPING = 'Sleeping'
    # Going home because battery is depleted
    RECHARGE_NEEDED = 'Recharge'
    RECHARGE = 'Recharge'
    # In the dock, full charged
    COMPLETED = 'Completed'
    STANDBY = 'Standby'
    SLEEP = 'Sleep'
    FAULT = 'Fault'
    FAST_MAPPING = 'Fast Mapping'
    CLEANING = 'Cleaning'
    REMOTE_CTRL = 'Remote Ctrl'
    GO_HOME = 'Go Home'
    CRUISIING = 'Cruising'


class EUFY_CLEAN_WORK_MODE(str, Enum):
    AUTO = 'auto'
    NO_SWEEP = 'Nosweep'
    SMALL_ROOM = 'SmallRoom'
    ROOM = 'room'
    ZONE = 'zone'
    EDGE = 'Edge'
    SPOT = 'Spot'


class EUFY_CLEAN_CONTROL(int, Enum):
    START_AUTO_CLEAN = 0
    START_SELECT_ROOMS_CLEAN = 1
    START_SELECT_ZONES_CLEAN = 2
    START_SPOT_CLEAN = 3
    START_GOTO_CLEAN = 4
    START_RC_CLEAN = 5
    START_GOHOME = 6
    START_SCHEDULE_AUTO_CLEAN = 7
    START_SCHEDULE_ROOMS_CLEAN = 8
    START_FAST_MAPPING = 9
    START_GOWASH = 10
    STOP_TASK = 12
    PAUSE_TASK = 13
    RESUME_TASK = 14
    STOP_GOHOME = 15
    STOP_RC_CLEAN = 16
    STOP_GOWASH = 17
    STOP_SMART_FOLLOW = 18
    START_GLOBAL_CRUISE = 20
    START_POINT_CRUISE = 21
    START_ZONES_CRUISE = 22
    START_SCHEDULE_CRUISE = 23
    START_SCENE_CLEAN = 24
    START_MAPPING_THEN_CLEAN = 25


EUFY_CLEAN_ERROR_CODES = {
    0: 'NONE',
    1: 'CRASH BUFFER STUCK',
    2: 'WHEEL STUCK',
    3: 'SIDE BRUSH STUCK',
    4: 'ROLLING BRUSH STUCK',
    5: 'HOST TRAPPED CLEAR OBST',
    6: 'MACHINE TRAPPED MOVE',
    7: 'WHEEL OVERHANGING',
    8: 'POWER LOW SHUTDOWN',
    13: 'HOST TILTED',
    14: 'NO DUST BOX',
    17: 'FORBIDDEN AREA DETECTED',
    18: 'LASER COVER STUCK',
    19: 'LASER SENSOR STUCK',
    20: 'LASER BLOCKED',
    21: 'DOCK FAILED',
    26: 'POWER APPOINT START FAIL',
    31: 'SUCTION PORT OBSTRUCTION',
    32: 'WIPE HOLDER MOTOR STUCK',
    33: 'WIPING BRACKET MOTOR STUCK',
    39: 'POSITIONING FAIL CLEAN END',
    40: 'MOP CLOTH DISLODGED',
    41: 'AIRDRYER HEATER ABNORMAL',
    50: 'MACHINE ON CARPET',
    51: 'CAMERA BLOCK',
    52: 'UNABLE LEAVE STATION',
    55: 'EXPLORING STATION FAIL',
    70: 'CLEAN DUST COLLECTOR',
    71: 'WALL SENSOR FAIL',
    72: 'ROBOVAC LOW WATER',
    73: 'DIRTY TANK FULL',
    74: 'CLEAN WATER LOW',
    75: 'WATER TANK ABSENT',
    76: 'CAMERA ABNORMAL',
    77: '3D TOF ABNORMAL',
    78: 'ULTRASONIC ABNORMAL',
    79: 'CLEAN TRAY NOT INSTALLED',
    80: 'ROBOVAC COMM FAIL',
    81: 'SEWAGE TANK LEAK',
    82: 'CLEAN TRAY NEEDS CLEAN',
    83: 'POOR CHARGING CONTACT',
    101: 'BATTERY ABNORMAL',
    102: 'WHEEL MODULE ABNORMAL',
    103: 'SIDE BRUSH ABNORMAL',
    104: 'FAN ABNORMAL',
    105: 'ROLLER BRUSH MOTOR ABNORMAL',
    106: 'HOST PUMP ABNORMAL',
    107: 'LASER SENSOR ABNORMAL',
    111: 'ROTATION MOTOR ABNORMAL',
    112: 'LIFT MOTOR ABNORMAL',
    113: 'WATER SPRAY ABNORMAL',
    114: 'WATER PUMP ABNORMAL',
    117: 'ULTRASONIC ABNORMAL',
    119: 'WIFI BLUETOOTH ABNORMAL',
    1013: 'LEFT WHEEL OVERCURRENT',
    1023: 'RIGHT WHEEL OVERCURRENT',
    1033: 'LEFT RIGHT WHEEL OVERCURRENT',
    1010: 'LEFT WHEEL OPEN CIRCUIT',
    1011: 'LEFT WHEEL SHORT CIRCUIT',
    1012: 'LEFT WHEEL ABNORMAL',
    1020: 'RIGHT WHEEL OPEN CIRCUIT',
    1021: 'RIGHT WHEEL SHORT CIRCUIT',
    1022: 'RIGHT WHEEL ABNORMAL',
    1030: 'LEFT RIGHT WHEEL OPEN CIRCUIT',
    1031: 'LEFT RIGHT WHEEL SHORT CIRCUIT',
    1032: 'LEFT RIGHT WHEEL ABNORMAL',
    2013: 'SINGLE FAN ROTATION ABNORMAL',
    2023: 'LEFT FAN ROTATION ABNORMAL',
    2027: 'RIGHT FAN ROTATION ABNORMAL',
    2010: 'SINGLE FAN OPEN CIRCUIT',
    2011: 'SINGLE FAN SHORT CIRCUIT',
    2012: 'SINGLE FAN ABNORMAL',
    2020: 'LEFT FAN OPEN CIRCUIT',
    2021: 'LEFT FAN SHORT CIRCUIT',
    2022: 'LEFT FAN ABNORMAL',
    2024: 'RIGHT FAN OPEN CIRCUIT',
    2025: 'RIGHT FAN SHORT CIRCUIT',
    2026: 'RIGHT FAN ABNORMAL',
    2112: 'SINGLE BRUSH OVERCURRENT',
    2122: 'DOUBLE BRUSH FRONT OVERCURRENT',
    2125: 'DOUBLE BRUSH BACK OVERCURRENT',
    2110: 'SINGLE BRUSH OPEN CIRCUIT',
    2111: 'SINGLE BRUSH SHORT CIRCUIT',
    2113: 'SINGLE BRUSH ABNORMAL',
    2120: 'DOUBLE BRUSH FRONT OPEN CIRCUIT',
    2121: 'DOUBLE BRUSH FRONT SHORT CIRCUIT',
    2123: 'DOUBLE BRUSH BACK OPEN CIRCUIT',
    2124: 'DOUBLE BRUSH BACK SHORT CIRCUIT',
    2213: 'SINGLE SIDE BRUSH OVERCURRENT',
    2223: 'LEFT SIDE BRUSH OVERCURRENT',
    2227: 'RIGHT SIDE BRUSH OVERCURRENT',
    2210: 'SINGLE SIDE BRUSH OPEN CIRCUIT',
    2211: 'SINGLE SIDE BRUSH SHORT CIRCUIT',
    2212: 'SINGLE SIDE BRUSH ABNORMAL',
    2220: 'LEFT SIDE BRUSH OPEN CIRCUIT',
    2221: 'LEFT SIDE BRUSH SHORT CIRCUIT',
    2222: 'LEFT SIDE BRUSH ABNORMAL',
    2224: 'RIGHT SIDE BRUSH OPEN CIRCUIT',
    2225: 'RIGHT SIDE BRUSH SHORT CIRCUIT',
    2226: 'RIGHT SIDE BRUSH ABNORMAL',
    2310: 'DUSTBIN NOT INSTALLED',
    2311: 'DUSTBIN INSTALLED USE TIME EXCEEDS 10 HOURS',
    3013: 'ROBOT WATER TANK INSUFFICIENT',
    3010: 'ROBOT WATER PUMP OPEN CIRCUIT',
    3011: 'ROBOT WATER PUMP SHORT CIRCUIT',
    3012: 'ROBOT WATER TANK WATER PUMP ABNORMAL',
    3020: 'ROBOT WATER TANK REMOVED CANNOT MOVE',
    3110: 'LEFT MOP NOT INSTALLED',
    3111: 'RIGHT MOP NOT INSTALLED',
    3123: 'ROTATING MOTOR JAMMED',
    3133: 'LIFTING MOTOR JAMMED',
    3120: 'ROTATING MOTOR OPEN CIRCUIT',
    3121: 'ROTATING MOTOR SHORT CIRCUIT',
    3122: 'ROTATING MOTOR ABNORMAL',
    3130: 'LIFTING MOTOR OPEN CIRCUIT',
    3131: 'LIFTING MOTOR SHORT CIRCUIT',
    3132: 'LIFTING MOTOR ABNORMAL',
    4012: 'RADAR ROTATION ABNORMAL',
    4011: 'RADAR BLOCKED',
    4010: 'RADAR NO SIGNAL COMMUNICATION POSSIBLY DAMAGED',
    4020: 'GYROSCOPE ABNORMAL',
    4030: 'TOF NO SIGNAL COMMUNICATION POSSIBLY DAMAGED',
    4031: 'TOF BLOCKED',
    4040: 'CAM NO SIGNAL COMMUNICATION POSSIBLY DAMAGED',
    4041: 'CAM BLOCKED',
    4090: 'WALL SENSOR NO SIGNAL COMMUNICATION POSSIBLY DAMAGED',
    4091: 'WALL SENSOR BLOCKED',
    4111: 'LEFT FRONT COLLISION LONG TRIGGER',
    4112: 'RIGHT FRONT COLLISION LONG TRIGGER',
    4120: 'ULTRASONIC COMMUNICATION INTERRUPTED CLEANING SCENE',
    4121: 'ULTRASONIC COMMUNICATION INTERRUPTED NON CLEANING SCENE',
    4130: 'LASER SHIELD LONG TRIGGER',
    5012: 'BATTERY CHARGING CURRENT TOO SMALL',
    5010: 'BATTERY OPEN CIRCUIT',
    5011: 'BATTERY SHORT CIRCUIT',
    5013: 'BATTERY DISCHARGE CURRENT TOO LARGE',
    5016: 'CHARGING CURRENT TOO LARGE',
    5017: 'CHARGING VOLTAGE ABNORMAL',
    5018: 'BATTERY TEMPERATURE ABNORMAL',
    5021: 'DISCHARGE HIGH TEMPERATURE',
    5022: 'DISCHARGE LOW TEMPERATURE',
    5023: 'CHARGING HIGH TEMPERATURE',
    5024: 'CHARGING LOW TEMPERATURE',
    5014: 'LOW BATTERY SHUTDOWN',
    5015: 'LOW BATTERY CANNOT SCHEDULE CLEANING',
    5110: 'WIFI ABNORMAL',
    5111: 'BT ABNORMAL',
    5112: 'INFRARED COMMUNICATION ABNORMAL',
    6010: 'CLEAN WATER TANK NOT INSTALLED',
    6020: 'DIRTY WATER TANK NOT INSTALLED',
    6025: 'DIRTY WATER TANK ABNORMAL FULL OR NOT INSTALLED',
    6011: 'CLEAN WATER TANK EMPTY',
    6021: 'DIRTY WATER TANK FULL',
    6012: 'CLEAN WATER PUMP OPEN CIRCUIT',
    6013: 'CLEAN WATER PUMP SHORT CIRCUIT',
    6014: 'THREE WAY VALVE SHORT CIRCUIT',
    6022: 'DIRTY WATER PUMP OPEN CIRCUIT',
    6023: 'DIRTY WATER PUMP SHORT CIRCUIT',
    6024: 'DIRTY WATER TANK NOT CLOSED TIGHTLY',
    6030: 'CLEANING DISC NOT INSTALLED',
    6031: 'CLEANING DISC WATER FULL',
    6032: 'CLEANING DISC NOT INSTALLED OR WATER FULL',
    6040: 'BLOWING FAN OPEN CIRCUIT',
    6041: 'BLOWING FAN SHORT CIRCUIT',
    6042: 'HEATING MODULE OPEN CIRCUIT',
    6043: 'NTC OPEN CIRCUIT',
    6110: 'VOLTAGE TRANSFORMER DEGREE ABNORMAL',
    6111: 'DUST BIN LEAKS AIR',
    6112: 'DUST BIN BLOCKED',
    6113: 'DUST BAG NOT INSTALLED',
    6114: 'FAN OVERHEATED',
    6115: 'PRESSURE GAUGE ABNORMAL',
    6300: 'HAIR CLEANING IN PROGRESS',
    6301: 'LOW BATTERY CANNOT START HAIR CUTTING',
    6310: 'POWER FAILURE',
    6311: 'HAIR CUTTING COMPONENT ABNORMAL OR BLOCKED CANNOT START WORK',
    7000: 'SMALL SPACE TIMEOUT',
    7001: 'PART OF MACHINE SUSPENDED',
    7004: 'MACHINE STUCK',
    7002: 'MACHINE PICKED UP EXCEEDING 3 GROUND CHECKS WHEEL SUSPENDED',
    7003: 'STARTUP FALLING SUSPENDED',
    7010: 'ENTERED FORBIDDEN AREA',
    7011: 'ENTERED CARPET',
    7020: 'POSITIONING FAILED IN GLOBAL CLEANING',
    7021: 'POSITIONING FAILED IN NON GLOBAL CLEANING',
    7031: 'RIDING FAILURE',
    7035: 'RIDING FAILURE BASE STATION NOT POWERED ON',
    7036: 'RIDING FAILURE OMNIWHEEL JAMMED',
    7037: 'RIDING FAILURE INFRARED REFLECTION',
    7033: 'EXPLORING BASE STATION FAILURE BASE STATION DEPARTURE',
    7034: 'CANNOT FIND STARTING POINT',
    7040: 'DISMOUNT FAILURE',
    7050: 'CANNOT REACH',
    7051: 'SCHEDULE FAILURE',
    7052: 'PATH PLANNING FAILURE',
    7053: 'MACHINE TILTED',
    7055: 'STATION NOT FOUND CANNOT MOP',
}
